### ISSUE TITLE
Async functions for keygen, presence and me

### ISSUE THREAD

**Issue by postacik** [emitter-io/javascript#11]
Is it possible to implement async versions of keygen, presence (status = true, changes = false) and me functions?

For example:

```
var response = await keygenAsync({ key: key_, channel: channel_, ttl: 60 });
console.log(response.key);

```
I can implement it myself but since there is global event handler for all three requests, I have to find a way to match the request I send with the response I get.

Do emitter requests have an id which I can use for this purpose?

**Comment by kelindar** [comment]
Should be possible indeed, we did something similar in the new Go client. I've used a map to dispatch the responses back: https://github.com/emitter-io/go/blob/master/v2/emitter.go#L400-L417

Feel free to contribute back!

**Comment by kelindar** [comment]
Here's what happens in Go library to make this work. I need to highlight that for this to work you'd need to send presence/keygen/me publish messages with QoS = 1.

1. [client] with `QoS=1`, the client generates a `MessageID` which goes into the MQTT header
2. [client] adds the callback with `MessageID` key into a map and waits for a response or an error
3. [broker] receives the Publish, gets the `MessageID` and adds it into as a `req` into the JSON
4. [client] receives the Publish (reponse or error) and looks for a `req` key in the JSON response, if present invokes the appropriate callback

**Comment by postacik** [comment]
After your explanation, I noticed that the mqtt library I use in Flutter returns a message identifier when it calls publishMessage function.

Is that the same for the Javascript mqtt library?

**Comment by postacik** [comment]
@Florimond ,

I applied @kelindar 's instructions to the C# GenerateKey function.

I used QoS = 1 calling the Publish1 function.

```
        public ushort GenerateKey(string secretKey, string channel, SecurityAccess securityAccess, int ttl, KeygenHandler handler)
        {
            // Prepare the request
            var request = new KeygenRequest();
            request.Key = secretKey;
            request.Channel = channel;
            request.Type = securityAccess;
            request.Ttl = ttl;

            // Register the handler
            this.KeygenHandlers[channel] = handler;

            // Serialize and publish the request
            return this.Publish1("emitter/", "keygen/", Encoding.UTF8.GetBytes(request.ToJson()));
        }

```

```
        public ushort Publish1(string key, string channel, byte[] message)
        {
            return this.Client.Publish(FormatChannel(key, channel), message, MqttMsgBase.QOS_LEVEL_AT_LEAST_ONCE, false);
        }


```

But in the OnMqttMsgPublishReceived event handler, messageId always equals to zero.

![image](https://user-images.githubusercontent.com/3977227/56497976-734bc500-6508-11e9-8d87-445c31d23de4.png)

Any ideas?

**Comment by postacik** [comment]
I also tried with my Dart library to see if the problem was with the C# mqtt library.

In the Dart library I send keygen message with QoS = 1.

```
  keygen(String key, String channel, String type, int ttl) {
    var request = {"key": key, "channel": channel, "type": type, "ttl": ttl};
    _mqtt.publishMessage(
        "emitter/keygen/", MqttQos.atLeastOnce, _payload(jsonEncode(request)));
    return this;
  }

```

However the response to the keygen message has a message id = 0 just like with the C# library.

PS: I made the Dart tests with Emitter cloud.

**Comment by postacik** [comment]
Ok, I figured it out.

I was looking for a message id in the mqtt message because I did not read @kelindar 's instructions carefully.

Instead, I have to match the message id of the publish request with the `req` value in the JSON response.

@Florimond , is it possible to implement this in the Javascript and C# libraries?

Thanks :)
