### ISSUE TITLE
How to modify and rebuild?

### ISSUE THREAD

**Issue by postacik** [emitter-io/javascript#12]
Hi,
I want to add some async functions to the library.

What is the proper way of modifying this library and rebuild it?

Should I modify emitter.ts in the lib directory?

**Comment by postacik** [comment]
Any comments?

**Comment by Florimond** [comment]
Yes, it's the typescript that you should modify.
You compile typescript in VS code with ctrl+shift+b.

You can generate the final file (uglified and all) using grunt.

```
npm install -g grunt-cli
npm install -S grunt
grunt
```

**Comment by postacik** [comment]
Thanks, it worked. Can you put this info into readme?
