### ISSUE TITLE
Unable to connect using the free account

### ISSUE THREAD

**Issue by jstolz** [emitter-io/javascript#13]
Hi,
I use emitter.io in an Angular and in a dotnetcore application. Both application now throw an exception if I try to connect => the last successfull connect was 2019-05-10. I updated the Angular version to 1.38.0 but the problem is still same. I didn´t modified the sources in the last 2 weeks.

The Angular application returns 
stream.js:43 WebSocket connection to 'ws://api.emitter.io:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

and the dotnetcore throws
ExtendedSocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 35.193.233.222:8080 (No connection could be established because the target computer refused the connection.)
2019-05-16 17:22:24,607 [10] FATAL TheHaulierApi.Services.Emitter_IO.EmitterIOService - EmitterIOService(..), Exception: Exception connecting to the broker

It is not a firewall problem, the connect failed in local and the deployed (Azure) versions.

Any idea, hint?
Regards
Juergen

**Comment by Florimond** [comment]
Emitter has just shut down the cloud. See [issue 233](https://github.com/emitter-io/emitter/issues/233)

**Comment by jstolz** [comment]
Thanks to everyone, what are you doing now? Do you continue to use Emitter.io or switch to another Message Broker?
Like RabbitMq

**Comment by Florimond** [comment]
Only the cloud hosted by the project has been shut down. As an open source project, Emitter still exists, and will be maintained.
You just have to deploy your own server(s), like you would with RabbitMQ. There are video tutorials on to do that here: [Kel on youtube](https://www.youtube.com/watch?v=CsrKiNjZ2Ew&list=PLhFXrq-2gEb3XMFwG8fhimC0CV46NrYrQ)
