### ISSUE TITLE
Using in React

### ISSUE THREAD

**Issue by young-versacall** [emitter-io/javascript#4]
I've been struggling trying to get this to work in React.  Does anyone have any guidance for making that work?  I've tried manually importing the emitter.min.js in the index.html but I just get more errors I think because it is missing some dependencies.

**Comment by Florimond** [comment]
I am no React dev myself, but what I did is

`npx create-react-app my-app`

Then I installed emitter with nmp install emitter-io

Then I modified the app.js to obtain the following :

(sorry for the format, it's not me, it's github)

`
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
var emitter = require('emitter-io')

class App extends Component
{
    constructor(props) 
	{                                                        
        super(props)                                                            
        //this.someFunction = this.someFunction.bind(this)
		let client = emitter.connect(); 
		client.subscribe({
			key: "YgBLv3zD4e2Vz_jdZUR1ojZlJiABlhTD",
			channel: "test"
		});
		
		client.on('message', function(msg){
			console.log( msg.asString() );
		});

		// publish a message to the chat channel
		client.publish({
			key: "YgBLv3zD4e2Vz_jdZUR1ojZlJiABlhTD",
			channel: "test",
			message: "hello, emitter!"
		});
    }    
	
  render() {
    return (
  ...
`

And this works fine. But maybe I'm not using React the proper way? Tell me more about how you do it...

**Comment by Florimond** [comment]
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
var emitter = require('emitter-io')

class App extends Component
{
    constructor(props) 
	{                                                        
        super(props)                                                            
        //this.someFunction = this.someFunction.bind(this)
		let client = emitter.connect(); 
		client.subscribe({
			key: "YgBLv3zD4e2Vz_jdZUR1ojZlJiABlhTD",
			channel: "test"
		});
		
		client.on('message', function(msg){
			console.log( msg.asString() );
		});

		// publish a message to the chat channel
		client.publish({
			key: "YgBLv3zD4e2Vz_jdZUR1ojZlJiABlhTD",
			channel: "test",
			message: "hello, emitter!"
		});
    }    
	
  render() {
	//let client = Emitter.connect(); 
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;

**Comment by fauzanmasulili** [comment]
how to pass message to state?

**Comment by Florimond** [comment]
Not sure I understand the issue... You can register any function in `client.on('message')`, including an arrow function of the component. From this arrow function, can't you just do `this.setState({...})` ?

**Comment by fauzanmasulili** [comment]
thanks, man it works with arrow function

**Comment by fauzanmasulili** [comment]
thanks man, it works using an arrow function
