### ISSUE TITLE
Does not auto-reconnect

### ISSUE THREAD

**Issue by marufbd** [emitter-io/javascript#9]
If i restart the broker, the client does not auto-reconnect.

But npm doc, connect() says it automatically reconnects.

**Comment by Florimond** [comment]
I do not reproduce this behavior.
![image](https://user-images.githubusercontent.com/372102/53946618-760f6980-40c4-11e9-812a-f6d2cb80a909.png)

I restarted the broker and, as you can see, it tried to reconnect automatically several times until it succeeded.

However, you'll still have to re-subscribe to the channels, which you can do in the `connect` handler.
